language: python
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pyqt5
  - ln -s /usr/lib/python3/dist-packages/PyQt5 $VIRTUAL_ENV/lib/python${TRAVIS_PYTHON_VERSION}/site-packages/PyQt5
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -e .[all,plots]
  - pip install pytest-cov
script:
  - pytest --cov=mushroom_rl --cov-report=xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
