language: python
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e .[all,plots]
  - pip install pytest-cov
script:
  - pytest --cov=mushroom_rl --cov-report=xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
